POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsenUxIiwiaWQiOiI2MjJiNTRmNGVhODZmNDIyOGNlNjcyNTciLCJpYXQiOjE2NDcwMDcwMDl9.bTyeUZmUNamOjB92BzrIxrqw33PAVg7HHGh699iqDGc

{
  "title": "commment test",
  "author": "test Hel",
  "url": "http://testest.com",
  "likes": "9000"
}

###

GET http://localhost:3003/api/blogs/625c265c9beecd71a40642cf
Content-Type: application/json


###
post http://localhost:3003/api/users
Content-Type: application/json

  {
      "username": "ternoa",
      "name": "Alfonz Terno",
      "password": "Alfonz&333"
  }